<?php

  define('E_SUCCESS', 0);

  define('E_BRICKS_BRICKS_NOT_FOUND', 2001);
  define('E_BRICKS_SETS_NOT_FOUND', 3001);
  define('E_BRICKS_COLORS_NOT_FOUND', 5001);
  define('E_BRICKS_INSTRUCTION_NOT_FOUND', 6002);

  define('E_BRICKS_SET_CATEGORIES_NOT_FOUND', 7001);
  define('E_BRICKS_SET_CATEGORY_NOT_FOUND', 7002);

  define('E_BRICKS_BRICK_CATEGORIES_NOT_FOUND', 8001);
  define('E_BRICKS_BRICK_CATEGORY_NOT_FOUND', 8002);

  define('E_BRICKS_BRICK_PRICES_NOT_FOUND', 9001);

  define('E_BRICKS_CATEGORY_SETS_NOT_FOUND', 10001);
  
  define('E_DATA_OBJECT_NOT_EXISTS', 106);
  

?>